# Generated by Django 5.0.4 on 2024-05-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_media', '0002_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='categories',
            field=models.ManyToManyField(blank=True, to='uploaded_media.category'),
        ),
    ]
