# Generated by Django 5.0.4 on 2024-05-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_media', '0003_category_image_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
