# Generated by Django 5.0.4 on 2024-05-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='menus',
        ),
        migrations.AddField(
            model_name='menu',
            name='pages',
            field=models.ManyToManyField(blank=True, to='pages.page'),
        ),
    ]
