# Generated by Django 5.0.4 on 2024-05-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_is_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('Fullwidth', 'Full Width'), ('Container', 'Container'), ('Fullwidth with header', 'Full Width With Header'), ('Container with header', 'Container With Header')], default='Container', max_length=100),
        ),
    ]
