# Generated by Django 5.0.4 on 2024-05-02 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaImaga',
            new_name='MediaImage',
        ),
    ]
