# Generated by Django 5.0.4 on 2024-05-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_featured_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaImage',
        ),
    ]
