# Generated by Django 5.0.4 on 2024-05-03 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('blog', '0012_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.author'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
