# Generated by Django 5.0.4 on 2024-05-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
    ]
